config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'welcome/home'
  get 'states/fetch_country_states'

  devise_for :users , controllers: { registrations: "user/registrations" ,  }

  resources :books do
    collection do
      post :import
    end
  end
  resources :users do
    resources :addresses
    # collection do
    #   get :fetch_country_states
    # end
    member do
      get :showbh
    end
    collection do
      get :student
      get :student_csv
      post :import
    end
  end
  resources :borrow_histories
  resources :countries
  resources :states

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'welcome#home'
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  require 'csv'
  require 'open-uri'
  has_many :books, dependent: :destroy
  has_many :borrow_histories, dependent: :destroy
  has_many :addresses, dependent: :destroy, inverse_of: :user
  has_one_attached :image
  accepts_nested_attributes_for :addresses , allow_destroy: true
  scope :std_list, lambda { where(role: 'student') }
  scope :lib_list, lambda { where(role: 'libraian') }
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :validatable,
         authentication_keys: [:login]

  attr_accessor :login

  ROLE_LIST = %w[student libraian].freeze

  validates :user_name, presence: true

  def login
    @login || email || user_name
  end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    login = conditions.delete(:login)
    where(conditions).where(['lower(user_name) = :value OR lower(email) = :value',
                             { value: login.strip.downcase }]).first
  end

  after_create :send_welcome_email

  def send_welcome_email
    # debugger
    UserMailer.send_welcome(self).deliver!
  end

  def self.to_csv
    attributes = %w{ id user_name email }
    CSV.generate(headers: true) do |csv|
      csv << attributes
      all.each do |student|
        csv << attributes.map { |attr| student.send(attr)  }
      end
    end
  end
  def grab_image(url)
    img = open(url)
    image.attach(io: img, filename: 'pic.png')
  end

end

app/controllers/user/confirmations_controller.rb
# frozen_string_literal: true

class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/user/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/user/passwords_controller.rb
# frozen_string_literal: true

class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/user/registrations_controller.rb
# frozen_string_literal: true

class User::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end


  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
  protected def update_resource(resource, params)
    return super if params["password"]&.present?
    resource.update_without_password(params.except("current_password"))
  end
end

app/controllers/user/sessions_controller.rb
# frozen_string_literal: true

class User::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/user/unlocks_controller.rb
# frozen_string_literal: true

class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  load_and_authorize_resource
  def index
    @q = User.ransack(params[:q])
    @pagy, @users = pagy_countless(@q.result(distinct: true).std_list.order(created_at: :asc), items: 6) if  params[:q].present?
    @pagy, @users = pagy_countless(@q.result(distinct: true).lib_list.order(created_at: :asc), items: 6) if  params[:q].present?

    @users = User.std_list if params[:show] == 'student_list'
    @users = User.lib_list if params[:show] == 'librarian_list'
  end

  def student
    @std = User.std_list
    respond_to do |format|
      format.html
      format.pdf do
        # render pdf: "Users: #{@users.count}", template: "users/index.html.erb" # Excluding ".pdf" extension.
        render pdf: "Students.pdf", template: "users/student", formats: [:html]
      end
      end
  end

  def student_csv
    @std = User.std_list
    respond_to do |format|
      format.html
      format.csv { send_data @std.to_csv }
    end
  end

  def import
    if params[:file].present?
      file = File.read(params[:file])
      csv = CSV.parse(file, headers: true, col_sep: ',')
      begin
        csv.each do |row|
          var = row.to_h.except('url')
          user = User.new(var)
          if user.save
            user.grab_image(row['url']) if row['url'].present?
          end
        end
        redirect_to welcome_home_path, notice: 'Stundent Updated Sucessfullt'
      rescue StandardError => e
        redirect_to welcome_home_path, notice: 'File format is not correct or data already exist'
      end
    else
      redirect_to welcome_home_path, notice: 'please select file'
    end
  end

  def show
    @student = User.find(params[:id])
  end

  def showbh
    @student = User.find(params[:id])
  end
  def fetch_country_states
    debugger
  end
  def destroy
    @student = User.find(params[:id])
    @student.destroy
    redirect_to users_path(show: 'student_list'), status: :see_other
  end
end

app/views/users/_sbhd.html.erb
<%= turbo_frame_tag :remote_modal, target: :_top do  %>
 <div class="modal fade" id="showModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true" data-controller="display" >
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header " style="background: #3B2F2F ; " >
        <h5 class="modal-title" id="exampleModalLabel" style="color: wheat; " >Borrowed Books</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close" data-action='click->display#disconnect'></button>
      </div>
        <% if @student.borrow_histories.any? %>
          <div class="modal-body " style="background: #C88141 ; " >
          <table class="table table-striped table-dark" style="text-align: center;margin: 10px;" >
          <thead>
          <th colspan="5" >Student Borrowed Books</th>
          </thead>
          <tbody>
          <tr>
            <td>User Name</td>
            <td>Book Name</td> 
            <td>Due Date</td>
            <td>Fine</td> 
          </tr>
          <% @student.borrow_histories.each do |b| %>
            <tr >
              <td><%= b.user.user_name %></td>
              <td><%= b.book&.title %></td>
              <td><%= b.due_date  %></td>
              <td> <%= b.fine %> </td>
              </tr>
          <% end %>
          </tbody>
        </table>
        <% else %>
          <h4 style="text-align: center;" >No Book Borrowed by this student</h4>
        <% end %>
      </div>
      <div class="modal-footer" style="background: #3B2F2F; " >
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal" data-action='click->display#disconnect'>Close</button>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/users/index.html.erb
<html>
  <head>
    <title>Home Page</title>
  </head>
  <div style="float: right; display: flex;" >
  <%= image_tag current_user.image, style: 'width: 50px; border-radius: 50px; ' if  current_user.image.attached? %>
    <h2 style="margin: auto" ><%= button_to 'Sign Out' , destroy_user_session_path, method: :delete , data: { confirm: '
                Do you want to sing out ? '}, data: { turbo: false }  %></h2>
  </div>
  <div style="float: right" >
    <%= search_form_for @q, data: { turbo_frame: :results } do |f| %>
      <%= f.label :Search , class: 'css_class', style: 'color:yellow; text-align: center; font-size: 25px; ' %>
      <%= f.search_field :user_name_or_email_cont, oninput: "this.form.requestSubmit()", autocomplete: "off"  , class: 'css_class', style: 'border: none; background: grey; ' %>
    <% end %>
  </div>
  <button class="btn btn-warning"  > <%= link_to 'Back' , welcome_home_path %> </button>
  <br>
  <div class="container">
    <body>
    <% if params[:show] == "librarian_list"%>
    <h1 style="text-align: center; color: Yellow">
    List of Librarian </h1>
    <%else%>
    <h1 style="text-align: center; color: Yellow">
    List of Studnets </h1>
      <% if current_user.role == "admin" %>
        <%= link_to 'Download PDF' , student_users_path(format: :pdf) , class: 'css_class', style: 'color:yellow; ' %>
        <%= link_to 'Download CSV' , student_csv_users_path(format: :csv) , class: 'css_class', style: 'color:yellow; ' %>
      <% end %>
    <%end%>

    <%= turbo_frame_tag :results do %>
      <table class="table table-striped table-dark">
        <thead>
        <th>User Name</th>
        <th>Eamil</th>
        <th>Role</th>
        <th colspan="4" style="text-align: center;" >Actions</th>
        </thead>
        <tbody>
        <% @users.each do |user| %>
          <tr id="user_id <%= user.id %>" >
            <td><%= user.user_name %></td>
            <td><%= user.email %></td>
            <td><%= user.role %></td>
            <td><button class="btn btn-outline-info" ><%= link_to 'View' , showbh_user_path(user) %></button></td>
            <% if user.role == 'student' %>
              <td> <button class="btn btn-outline-info"  ><%= link_to 'Borrowed List', user_path(user), data: { controller: 'try' } %></button> </td>
            <% end %>
            <% if can? :destroy, user %>
            <td>
              <%= button_to 'Delete' , user_path(user)  , method: :delete , data: { turbo: false }  %>
            </td>
              <% end %>
          </tr>
        <% end %>
        </tbody>

      </table>
      </body>
      <div style="color: yellow; float: right;" >
        <%== pagy_nav(@pagy) if @pagy.present? %>
      </div>
    <% end %>
  </div>

  <%# Modal Code Here %>
</html>

app/views/users/show.turbo_stream.erb
<%= turbo_stream.replace "remote_modal" do  %>
  <%= render "sbhd" %>
<% end %>

app/views/users/showbh.html.erb
<html>
<head>
  <title>  List </title>
  <style>
      hr {
          align-self: center;
          width: 50%;
      }
      h1{
          text-align: center;
          color: wheat;
      }
      h2{
          text-align: center;
          color: wheat;
      }
      p{
          text-align: center;
          color: wheat;
      }
  </style>
</head>
  <body>
    <br>
    <div class="container ">
    <% if current_user.role == "admin" || current_user.role == "libraian" %>
      <% if @student.role == "student" %>
      <button style="text-align: left"><%= link_to 'Back' , users_path(show: 'student_list') , class: 'css_class', style: 'color: blue; font-size: 25px;'%></button>  
      <% elsif @student.role == "libraian" %>
      <%# debugger %>
      <button style="text-align: left"><%= link_to 'Back' , users_path(show: 'librarian_list') , class: 'css_class', style: 'color: blue; font-size: 25px;'%></button>
       <% else %>
      <button style="text-align: left"><%= link_to 'Back' , welcome_home_path , class: 'css_class', style: 'color: blue; font-size: 25px;'%></button>
      <% end %>
      <% else %>
      <button style="text-align: left"><%= link_to 'Back' , welcome_home_path , class: 'css_class', style: 'color: blue; font-size: 25px;;'%></button>
    <% end %>
    
      <table class="table table-dark table-striped" style="text-align: center;margin: 10px;" >
        <thead>
          <th colspan="2" >List of the <%= @student.role %> </th>
        </thead>
        <tbody>
        <tr>
          <td>User Name</td>
          <td><%= @student.user_name %></td>
        </tr>
        <tr>
          <td>Email</td>
          <td><%= @student.email %></td>
        </tr>
        <tr>
          <td>Profile Picture</td>
          <td><%= image_tag @student.image, style: 'width: 50px; border-radius: 50px;}' if  @student.image.attached? %></td>
        </tr>
         <tr>
          <td>Joined</td>
          <td><%= time_ago_in_words(@student.created_at) %> ago</td>
        </tr>
        </tbody>
      </table>
      <hr>
      <% if @student.role == "student" && @student.borrow_histories.any? %>
        <table class="table table-striped table-dark" style="text-align: center;margin: 10px;" >
      <thead>
      <th colspan="5" >Student Borrowed Books</th>
      </thead>
      <tbody>
      <tr>
        <td > Student User Name </td>
        <td>Book Name</td>
        <td>Due Date</td>
        <td>Fine</td>
        <td>Actions</td>  
      </tr>
      <% @student.borrow_histories.each do |b| %>
        <tr >
          <td><%= b.user.user_name %></td>
          <td><%= b.book&.title %></td>
          <td><%= b.due_date  %></td>
          <td> <%= b.fine %> </td>
          <td>
            <%= button_to 'Delete' , borrow_history_path(b) ,method: :delete , data: { turbo: false } %>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
      <% end %>
    </div>

  <%# if @student.addresses.present? %>
<!--    <table class="table table-striped table-dark" style="text-align: center;margin: 10px;" >-->
<!--      <thead>-->
<!--      <th colspan="7" >Student Addresses</th>-->
<!--      </thead>-->
<!--      <tbody>-->
<!--      <tr>-->
<!--        <td> Address 1 </td>-->
<!--        <td>Address 2</td>-->
<!--        <td>Zipcode</td>-->
<!--        <td>City</td>-->
<!--        <td>State</td>-->
<!--        <td>Country</td>-->
<!--        <td>Action</td>-->
<!--      </tr>-->
      <%# @student.addresses.each do |address| %>
<!--        <tr >-->
<!--          <td><%#= address.address1 %></td>-->
<!--          <td><%#= address.address2 %></td>-->
<!--          <td><%#= address.zipcode  %></td>-->
<!--          <td> <%#= address.city %> </td>-->
<!--          <td> <%#= address.state %> </td>-->
<!--          <td> <%#= address.country %> </td>-->
<!--          <td><%#= button_to 'Delete' , user_address_path(address),method: :delete , data: { turbo: false }  %></td>-->
<!--          </tr>-->
      <%# end %>
<!--      </tbody>-->
<!--    </table>-->
    <%# end %>
  </body>
</html>

app/views/users/student.html.erb
<html>
<head>
  <title>Student Page</title>
</head>
<body>
<div class="container">
 <table class="table table-striped table-dark">
      <thead>
      <th>User ID</th>
      <th>User Name</th>
      <th>Email</th>
      <th>Role</th>
      </thead>
      <tbody>
      <% @std.each do |user| %>
        <td><%= user.id %></td>
        <td><%= user.user_name %></td>
        <td><%= user.email %></td>
        <td><%= user.role %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
</div>
</body>
</html>

app/views/users/student_csv.html.erb
<html>
<head>
  <title>Student Page</title>
</head>
<body>
<div class="container">
  <table class="table table-striped table-dark">
    <thead>
    <th>User ID</th>
    <th>User Name</th>
    <th>Email</th>
    <th>Role</th>
    </thead>
    <tbody>
    <% @std.each do |user| %>
      <td><%= user.id %></td>
      <td><%= user.user_name %></td>
      <td><%= user.email %></td>
      <td><%= user.role %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>
</body>
</html>