config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'welcome/home'
  get 'states/fetch_country_states'

  devise_for :users , controllers: { registrations: "user/registrations" ,  }

  resources :books do
    collection do
      post :import
    end
  end
  resources :users do
    resources :addresses
    # collection do
    #   get :fetch_country_states
    # end
    member do
      get :showbh
    end
    collection do
      get :student
      get :student_csv
      post :import
    end
  end
  resources :borrow_histories
  resources :countries
  resources :states

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'welcome#home'
end

app/models/state.rb
class State < ApplicationRecord
  belongs_to :country
  validates :state_name , :country_id , presence: :true , uniqueness: :true
end

app/controllers/states_controller.rb
class StatesController < ApplicationController
  def fetch_country_states
    @state = State.all.where(country_id: params[:id].to_i)
  end

  def index
    @q = State.ransack(params[:q])
    @pagy, @states = pagy_countless(@q.result(distinct: true).order(created_at: :asc), items: 7)
  end

  def edit
    @state = State.find(params[:id])
  end

  def show
    @state = State.find(params[:id])
  end

  def new
    @state = State.new
  end
  def create
    @state = State.new(state_params)
    if @state.save
      redirect_to state_path(@state)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @state = State.find(params[:id])
    if @state.update(state_params)
      redirect_to state_path
    else
      render :edit, status: :unprocessable_entity
    end
  end
  def destroy
    @state = State.find(params[:id])
    @state.destroy
    redirect_to states_path, status: :see_other
  end

  private
  def state_params
    params.require(:state).permit(:state_name, :country_id)
  end
end

app/helpers/states_helper.rb
module StatesHelper
end

app/views/states/edit.html.erb
<html>
<head>
  <style>
      .csform{
          text-align: center;
          margin: 10px;
      }
      .csform > label{
          align-self: center;
          color: whitesmoke;
      }
      .csform > input[type="text"]{
          background-color: wheat;
          border:none;
      }
      .csform > input[type="date"]{
          background-color: wheat;
          border:none;
      }
      .csform > input[type="submit"]{
          background-color: #3B0000 ;
          height: 100%;
          width: 100%;
          border-radius: 30px;
          border: none;
          padding: 10px;
          color: wheat;
      }
  </style>
</head>
<body>
<div style=" display: flex; justify-content: center">
  <div style="background-color: #8B4513; padding: 50px; margin: 30px; border-radius: 10px; ">
    <div style=" display: flex; justify-content: center">
      <%= form_with model: @state  do |form| %>
        <% if @state.errors.any? %>
          <% @stete.errors.full_messages.each do |message| %>
            <p style="text-align: center; color: wheat" ><%= message %></p>
          <% end %>
        <% end %>
        <div class="csform" >
          <%= form.label :State_Name %>
        </div>
        <div class="csform">
          <%= form.text_field :state_name %>
        </div>
        <div class="csform">
          <%= form.submit 'Edit State' %>
        </div>
        <div>
          <br><p style="text-align: center"><%= link_to 'Back' , state_path , class: 'css_class', style: 'color: wheat; text-align: center; ' %></p>
        </div>
      <% end %>
    </div>
  </div>
</div>
</body>
</html>

app/views/states/fetch_country_states.turbo_stream.erb
<%# if @state.present? %>
  <%#= turbo_stream.replace "country_state_list" do %>
    <option>Select State</option>
      <% @state.each do |state|  %>
        <option value="<%= state.state_name %>" >
          <%=  state.state_name  %>
        </option>
    <% end %>
  <%# end %>
<%# end %>

app/views/states/index.html.erb
<html>
<head>
  <title>Home Page</title>
</head>
<div style="float: right; display: flex;" >
  <%= image_tag current_user.image, style: 'width: 50px; border-radius: 50px; ' if  current_user.image.attached? %>
  <h2 style="margin: auto" ><%= button_to 'Sign Out' , destroy_user_session_path, method: :delete , data: { confirm: '
                Do you want to sing out ? '}, data: { turbo: false }  %></h2>
</div>
<div class="container">
  <body>
  <button class="btn btn-outline-warning btn-lg " > <%= link_to 'Back' , welcome_home_path , class: 'css_class', style: 'color:yellow; text-align: center; ' %> </button>
  <br>
  <button class="btn btn-outline-warning btn-lg " > <%= link_to 'Add New State' , new_state_path , class: 'css_class', style: 'color:yellow; text-align: center; ' %> </button>
  <div style="display: flex; justify-content: flex-end" >
    <%= search_form_for @q, data: { turbo_frame: :results } do |f| %>
      <%= f.label :Search , class: 'css_class', style: 'color:yellow; text-align: center; font-size: 25px; ' %>
      <%= f.search_field :state_name_cont, oninput: "this.form.requestSubmit()", autocomplete: "off"  , class: 'css_class', style: 'border: none; background: grey; ' %>
    <% end %>
  </div>
  <%= turbo_frame_tag :results do %>
    <table class="table table-striped table-dark">
      <thead>
      <th>State Name</th>
      <th colspan="3" style="text-align: center;" >Actions</th>
      </thead>
      <tbody>
      <tr>
        <% @states.each do |state| %>
          <td><%= state.state_name %></td>
          <td><button class="btn btn-outline-info" ><%= link_to 'View' , state_path(state) %></button></td>
          <td><button class="btn btn-outline-info"  ><%= link_to 'Edit' , edit_state_path(state) %></button> </td>
          <td><%= button_to 'Delete', state_path(state) ,method: :delete , data: { turbo: false }   %></td>
          </tr>
        <% end %>
        </tbody>
    </table>
    </body>
  <% end %>
  <div style="color: yellow; float: right;" >
    <%== pagy_nav(@pagy) %>
  </div>
</div>
</html>

app/views/states/new.html.erb
<html>
<head>
  <style>
      .csform{
          text-align: center;
          margin: 10px;
      }
      .csform > label{
          align-self: center;
          color: whitesmoke;
      }
      .csform > input[type="text"]{
          background-color: wheat;
          border:none;
      }
      .csform > input[type="date"]{
          background-color: wheat;
          border:none;
      }
      .csform > input[type="submit"]{
          background-color: #3B0000 ;
          height: 100%;
          width: 100%;
          border-radius: 30px;
          border: none;
          padding: 10px;
          color: wheat;
      }
  </style>
</head>
<body>
<div style=" display: flex; justify-content: center">
  <div style="background-color: #8B4513; padding: 50px; margin: 30px; border-radius: 10px; ">
    <div style=" display: flex; justify-content: center">
      <%= form_with model: @state  do |form| %>
        <% if @state.errors.any? %>
          <% @state.errors.full_messages.each do |message| %>
            <p style="text-align: center; color: wheat" ><%= message %></p>
          <% end %>
        <% end %>
        <div class="csform" >
          <%# debugger %>
          <%= form.seleact(:country_id, Country.all.collect {|u| [ u.country_name, u.id ]},{include_blank: "Select Country"}) %>
        </div>
        <div class="csform" >
          <%= form.label :State_Name %>
        </div>
        <div class="csform">
          <%= form.text_field :state_name %>
        </div>
        <div class="csform">
          <%= form.submit 'Add State' %>
        </div>
        <div>
          <br><p style="text-align: center"><%= link_to 'Back' , states_path , class: 'css_class', style: 'color: wheat; text-align: center; ' %></p>
        </div>
      <% end %>
    </div>
  </div>
</div>
</body>
</html>

app/views/states/show.html.erb
<html>
<head>
  <title> States List </title>
  <style>
      hr {
          align-self: center;
          width: 50%;
      }
      h1{
          text-align: center;
          color: wheat;
      }
      h2{
          text-align: center;
          color: wheat;
      }
      p{
          text-align: center;
          color: wheat;
      }
  </style>
</head>
<body>
<h1 style="text-align: center; color: yellow">States Detail</h1>
<br>
<h2 style="text-align: left;" ><%= link_to 'Back', states_path , class: 'css_class', style: 'color:yellow; text-align: center; ' %></h2>
<div class="container"  style="float: left;" >
  <table class="table table-dark table-striped" style="text-align: center;margin: 10px;'" >
    <thead>
    <tr>
      <th> State Name<th/>
    </tr>
    </thead>
    <tbody>
    <tr>
      <td><%= @state.state_name %></td>
    </tr>
    </tbody>
  </table>
  <hr>
</div>
</body>
</html>