config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'welcome/home'
  get 'states/fetch_country_states'

  devise_for :users , controllers: { registrations: "user/registrations" ,  }

  resources :books do
    collection do
      post :import
    end
  end
  resources :users do
    resources :addresses
    # collection do
    #   get :fetch_country_states
    # end
    member do
      get :showbh
    end
    collection do
      get :student
      get :student_csv
      post :import
    end
  end
  resources :borrow_histories
  resources :countries
  resources :states

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'welcome#home'
end

app/controllers/welcome_controller.rb
# frozen_string_literal: true

class WelcomeController < ApplicationController
  def home
    @user = User.find(current_user.id)
  end
end

app/views/welcome/home.html.erb
<html>
  <head>
    <title>Home Page</title>
    <style>
        .hep{
            float: right;
        }
        .form{
            color: yellow;
            font-size: 20px;
        }
    </style>
  </head>
  <div style="float: right; display: flex;" >
    <%= image_tag current_user.image, style: 'width: 50px; border-radius: 50px; ' if  current_user.image.attached? %>
    <h2 style="margin: auto" ><%=  button_to 'Sign Out' , destroy_user_session_path, method: :delete , data: { confirm: '
                Dp you want to sing out ? '}, data: { turbo: false }  %></h2>
  </div>
  <div class="container">
    <body>
    <h1 style="color: yellow; text-align: center;" > Welcome <%= current_user.user_name %> </h1>
      <div class="hep" >
        <button class="btn btn-outline-warning btn-lg"><%= link_to 'Edit Profile' , edit_user_registration_path , class: 'css_class', style: 'color:yellow;' %></button>
      <button class="btn btn-light btn-lg"> <%= link_to 'Personal Information', showbh_user_path(current_user.id) if can? :read, current_user , class: 'css_class', style: 'color:yellow;' %>  </button>
      </div>
      <% if current_user.role == 'admin' %>
        <button class="btn btn-outline-warning btn-lg" ><%= link_to 'Books Lidt' , books_path , class: 'css_class', style: 'color: yellow;' %></button>
        <button class="btn btn-outline-warning btn-lg"> <%= link_to 'Students List' , users_path(show: 'student_list') , class: 'css_ceElass', style: 'color:yellow;' %> </button>
        <button class="btn btn-outline-warning btn-lg"> <%= link_to 'Librarian List' , users_path(show: 'librarian_list') , class: 'css_class', style: 'color:yellow;' %> </button><br><br>
        <button class="btn btn-outline-warning btn-lg"><%= link_to 'Countries' , countries_path , class: 'css_class', style: 'color:yellow;' %></button>
        <button class="btn btn-outline-warning btn-lg"><%= link_to 'States' , states_path , class: 'css_class', style: 'color:yellow;' %></button><br><br>
        <div class="row" >
          <div class="form col"  >
            <h3>Import Books</h3>
            <%= form_with url: import_books_path, method: :post do |form| %>
              <%= form.file_field :file, accept: ".csv" ,class: 'css_class', style: 'color:yellow;'  %> <br><br>
              <%= form.button "Upload" , class: 'css_class', style: 'color:blue;  font-size: 20px;  ' %>
            <% end %>
          </div>
          <div class="form col-4" >
            <h3>Import Students</h3>
            <%= form_with url: import_users_path, method: :post do |form| %>
              <%= form.file_field :file, accept: ".csv" ,class: 'css_class', style: 'color:yellow;'  %> <br><br>
              <%= form.button "Upload" , class: 'css_class', style: 'color:blue;  font-size: 20px;  ' %>
            <% end %>
          </div>
        </div>
        <% elsif current_user.role == 'libraian' %>
        <button class="btn btn-outline-warning btn-lg" ><%= link_to 'Books List' , books_path , class: 'css_class', style: 'color:yellow;' %></button>
        <button class="btn btn-outline-warning btn-lg"> <%= link_to 'Students List' , users_path(show: 'student_list') , class: 'css_class', style: 'color:yellow;' %> </button>
        <% else  %>
        <button class="btn btn-outline-warning btn-lg" ><%= link_to 'Books Lidt' , books_path , class: 'css_class', style: 'color:yellow;' %></button>
      <% end %>
    </body>
  </div>
  

</html>