config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'welcome/home'
  get 'states/fetch_country_states'

  devise_for :users , controllers: { registrations: "user/registrations" ,  }

  resources :books do
    collection do
      post :import
    end
  end
  resources :users do
    resources :addresses
    # collection do
    #   get :fetch_country_states
    # end
    member do
      get :showbh
    end
    collection do
      get :student
      get :student_csv
      post :import
    end
  end
  resources :borrow_histories
  resources :countries
  resources :states

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'welcome#home'
end

app/models/country.rb
class Country < ApplicationRecord
  has_many :states , dependent: :destroy
  validates :country_name , presence: :true , uniqueness: :true
end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController
  def index
    @countries = Country.all
    @q = Country.ransack(params[:q])
    @pagy, @countries = pagy_countless(@q.result(distinct: true).order(created_at: :asc), items: 4)
    respond_to do |format|
      format.html
      format.pdf do
        # render pdf: "Countries.pdf", template: "countries/index.html.erb" # Excluding ".pdf" extension.
        render pdf: "Countries.pdf", template: "countries/index", formats: [:html]

      end
    end
  end

  def edit
    @country = Country.find(params[:id])
  end

  def show
    @country = Country.find(params[:id])
  end

  def new
    @country = Country.new
  end
  def create
    @country = Country.new(country_params)
    if @country.save
      redirect_to country_path(@country)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @country = Country.find(params[:id])
    if @country.update(country_params)
      redirect_to country_path
    else
      render :edit, status: :unprocessable_entity
    end
  end
  def destroy
    @country = Country.find(params[:id])
    @country.destroy
    redirect_to countries_path, status: :see_other
  end

  private
  def country_params
    params.require(:country).permit(:country_name)
  end
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/views/countries/edit.html.erb
<html>
<head>
  <style>
      .csform{
          text-align: center;
          margin: 10px;
      }
      .csform > label{
          align-self: center;
          color: whitesmoke;
      }
      .csform > input[type="text"]{
          background-color: wheat;
          border:none;
      }
      .csform > input[type="date"]{
          background-color: wheat;
          border:none;
      }
      .csform > input[type="submit"]{
          background-color: #3B0000 ;
          height: 100%;
          width: 100%;
          border-radius: 30px;
          border: none;
          padding: 10px;
          color: wheat;
      }
  </style>
</head>
<body>
<div style=" display: flex; justify-content: center">
  <div style="background-color: #8B4513; padding: 50px; margin: 30px; border-radius: 10px; ">
    <div style=" display: flex; justify-content: center">
      <%= form_with model: @country  do |form| %>
        <% if @country.errors.any? %>
          <% @country.errors.full_messages.each do |message| %>
            <p style="text-align: center; color: wheat" ><%= message %></p>
          <% end %>
        <% end %>
        <div class="csform" >
          <%= form.label :Country_Name %>
        </div>
        <div class="csform">
          <%= form.text_field :country_name %>
        </div>
        <div class="csform">
          <%= form.submit 'Edit Country' %>
        </div>
        <div>
          <br><p style="text-align: center"><%= link_to 'Back' , country_path , class: 'css_class', style: 'color: wheat; text-align: center; ' %></p>
        </div>
      <% end %>
    </div>
  </div>
</div>
</body>
</html>

app/views/countries/index.html.erb
<html>
<head>
  <title>Home Page</title>
</head>
<div style="float: right; display: flex;" >
  <%= image_tag current_user.image, style: 'width: 50px; border-radius: 50px; ' if  current_user.image.attached? %>
  <h2 style="margin: auto" ><%= button_to 'Sign Out' , destroy_user_session_path, method: :delete , data: { confirm: 'Do you want to sing out ? '}, data: { turbo: false }  %></h2>
</div>
<div class="container">
  <body>
  <button class="btn btn-outline-warning btn-lg " > <%= link_to 'Back' , welcome_home_path , class: 'css_class', style: 'color:yellow; text-align: center; ' %> </button>
  <br>
  <button class="btn btn-outline-warning btn-lg " > <%= link_to 'Add New Country' , new_country_path , class: 'css_class', style: 'color:yellow; text-align: center; ' %> </button>
  <div style="display: flex; justify-content: flex-end" >
    <%= search_form_for @q, data: { turbo_frame: :results } do |f| %>
      <%= f.label :Search , class: 'css_class', style: 'color:yellow; text-align: center; font-size: 25px; ' %>
      <%= f.search_field :country_name_cont, oninput: "this.form.requestSubmit()", autocomplete: "off"  , class: 'css_class', style: 'border: none; background: grey; ' %>
    <% end %>
  </div>
  <%= turbo_frame_tag :results do %>
  <table class="table table-striped table-dark">
    <thead>
    <th>Country Name</th>
    <th colspan="3" style="text-align: center;" >Actions</th>
    </thead>
    <tbody>
    <tr>
    <% @countries.each do |con| %>
        <td><%= con.country_name %></td>
        <td><button class="btn btn-outline-info" ><%= link_to 'View' , country_path(con) %></button></td>
        <td><button class="btn btn-outline-info"  ><%= link_to 'Edit' , edit_country_path(con) %></button> </td>
        <td><%= button_to 'Delete', country_path(con) ,method: :delete , data: { turbo: false }   %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
  <% end %>
  <div style="color: yellow; float: right;" >
    <%== pagy_nav(@pagy) %>
  </div>
  </body>
</div>
</html>

app/views/countries/new.html.erb
<html>
<head>
  <style>
      .csform{
          text-align: center;
          margin: 10px;
      }
      .csform > label{
          align-self: center;
          color: whitesmoke;
      }
      .csform > input[type="text"]{
          background-color: wheat;
          border:none;
      }
      .csform > input[type="date"]{
          background-color: wheat;
          border:none;
      }
      .csform > input[type="submit"]{
          background-color: #3B0000 ;
          height: 100%;
          width: 100%;
          border-radius: 30px;
          border: none;
          padding: 10px;
          color: wheat;
      }
  </style>
</head>
<body>
<div style=" display: flex; justify-content: center">
  <div style="background-color: #8B4513; padding: 50px; margin: 30px; border-radius: 10px; ">
    <div style=" display: flex; justify-content: center">
      <%= form_with model: @country  do |form| %>
        <% if @country.errors.any? %>
          <% @country.errors.full_messages.each do |message| %>
            <p style="text-align: center; color: wheat" ><%= message %></p>
          <% end %>
        <% end %>
        <div class="csform" >
          <%= form.label :Country_Name %>
        </div>
        <div class="csform">
          <%= form.text_field :country_name %>
        </div>
        <div class="csform">
          <%= form.submit 'Add Country' %>
        </div>
        <div>
          <br><p style="text-align: center"><%= link_to 'Back' , countries_path , class: 'css_class', style: 'color: wheat; text-align: center; ' %></p>
        </div>
      <% end %>
    </div>
  </div>
</div>
</body>
</html>

app/views/countries/show.html.erb
<html>
<head>
  <title> Countries List </title>
  <style>
      hr {
          align-self: center;
          width: 50%;
      }
      h1{
          text-align: center;
          color: wheat;
      }
      h2{
          text-align: center;
          color: wheat;
      }
      p{
          text-align: center;
          color: wheat;
      }
  </style>
</head>
<body>
<h1 style="text-align: center; color: yellow">Countries Detail</h1>
<br>
<h2 style="text-align: left;" ><%= link_to 'Back', countries_path , class: 'css_class', style: 'color:yellow; text-align: center; ' %></h2>
<div class="container"  style="float: left;" >
  <table class="table table-dark table-striped" style="text-align: center;margin: 10px;'" >
    <thead>
    <tr>
      <th>Country Name</th>
    </tr>
    </thead>
    <tbody>
    <tr><td><%= @country.country_name %></td></tr>
    </tbody>
  </table>
  <hr>
  <% if @country.states.any? %>
    <table class="table table-dark table-striped" style="text-align: center;margin: 10px;'" >
      <thead>
      <tr>
        <th>State Names</th>
      </tr>
      </thead>
      <tbody>
      <% @country.states.each do |s| %>
        <tr><td><%= s.state_name %></td></tr>
        <% end %>
      </tbody>
    </table>
  <% end %>
</div>
</body>
</html>